# docker-compose.yml

version: '3.8' 

services:
  nginx-proxy:
    image: nginx:stable-alpine
    ports:
      # Ánh xạ cổng 8080 của máy thật vào cổng 80 của container nginx
      - "8080:80"
    volumes:
      # Gắn file nginx.conf từ máy thật vào trong container
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
  
  app1:
    build: ./app

  app2:
    build: ./app 